name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: tests/shunit2

      - name: Build 1-debian-buster
        run: |
          ./build-image.sh $IMAGE_NAME 1 debian buster \
            1-debian-buster 1-debian debian 1 latest

      - name: Test 1-debian-buster
        run: tests/run $IMAGE_NAME:1-debian-buster

      - name: Build 1-alpine-3
        run: |
          ./build-image.sh $IMAGE_NAME 1 alpine 3 \
            1-alpine-3 1-alpine alpine

      - name: Test 1-alpine-3
        run: tests/run $IMAGE_NAME:1-alpine-3

      - name: Verify signature
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: atmoz/git-verify-ref@master
        with:
          import-github-users: atmoz

      - name: Push images to Docker Hub registry
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

          docker push $IMAGE_NAME # no tags specified to include all tags
          docker logout

      - name: Push images to GitHub registry
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com \
            -u ${{ github.actor }} --password-stdin

          TAG_DEBIAN=docker.pkg.github.com/$GITHUB_REPOSITORY/debian
          TAG_ALPINE=docker.pkg.github.com/$GITHUB_REPOSITORY/alpine
          docker tag $IMAGE_NAME:debian $TAG_DEBIAN
          docker tag $IMAGE_NAME:alpine $TAG_ALPINE
          docker push $TAG_DEBIAN
          docker push $TAG_ALPINE
          docker logout docker.pkg.github.com

