name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"

env:
  IMAGE_NAME: atmoz/sftp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: tests/shunit2

      - name: Verify signature
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: atmoz/git-verify-ref@master
        with:
          public_key_dir: .github/public-keys
