name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"

env:
  IMAGE_NAME: atmoz/sftp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@7ee62c0418c81f311c0fbf1b58a5d8423f6e008c
        with:
          ignore: tests/shunit2

      - name: secret
        run: echo ${{ secrets.SECRET }}

      - name: Verify signature
        run: |
          find .github/public-keys -type f -exec gpg --import {} \;
          git verify-commit HEAD

      - name: Verify signature
        uses: atmoz/git-verify-ref@master
        with:
          public_key_dir: .github/public-keys
